#!/usr/bin/env bash
#
# JARVIS credential bootstrap.
#
# Reads `.env.example` for the list of required environment variables and
# walks the user through populating `.env` interactively. Optionally posts a
# labelled smoke-test message via the Slack webhook to surface typos at setup
# time rather than at the next scheduled run.
#
# Usage:
#   $ bash scripts/init.sh
#
# Re-running: refuses to silently overwrite an existing `.env` and exits zero
# if the user declines the overwrite prompt.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

ENV_PATH="$REPO_ROOT/.env"
EXAMPLE_PATH="$REPO_ROOT/.env.example"

# ---- helpers --------------------------------------------------------------

die() {
  printf '[init] %s\n' "$*" >&2
  exit 1
}

note() {
  printf '[init] %s\n' "$*"
}

ask_yes_no() {
  # $1 prompt, $2 default ("Y" or "N")
  local prompt="$1" default="$2" reply suffix
  if [[ "$default" == "Y" ]]; then
    suffix=" [Y/n] "
  else
    suffix=" [y/N] "
  fi
  printf '%s%s' "$prompt" "$suffix"
  IFS= read -r reply
  reply="${reply:-$default}"
  [[ "$reply" =~ ^[Yy]$ ]]
}

# ---- preflight ------------------------------------------------------------

[[ -f "$EXAMPLE_PATH" ]] || die ".env.example is missing at $EXAMPLE_PATH"

# Validate the example file shape: every non-blank, non-comment line must be
# a KEY=... assignment. We bail before prompting if anything is malformed,
# so a botched `.env.example` cannot produce a half-written `.env`.
line_no=0
while IFS= read -r line || [[ -n "$line" ]]; do
  line_no=$((line_no + 1))
  [[ -z "$line" ]] && continue
  [[ "$line" =~ ^[[:space:]]*# ]] && continue
  if ! [[ "$line" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; then
    die ".env.example line $line_no is not blank, not a comment, and not a KEY= assignment: $line"
  fi
done < "$EXAMPLE_PATH"

# ---- existing-.env guard --------------------------------------------------

if [[ -f "$ENV_PATH" ]]; then
  note "Existing .env found at $ENV_PATH"
  if ! ask_yes_no "Overwrite it?" "N"; then
    note "Leaving existing .env untouched. Exiting."
    exit 0
  fi
fi

# ---- collect (comment, key) pairs in declaration order -------------------

declare -a KEYS
declare -a COMMENTS
pending_comment=""

while IFS= read -r line || [[ -n "$line" ]]; do
  if [[ -z "$line" ]]; then
    pending_comment=""
    continue
  fi
  if [[ "$line" =~ ^[[:space:]]*# ]]; then
    # Strip leading "# " for display
    cleaned="${line#"${line%%[![:space:]]*}"}"   # ltrim
    cleaned="${cleaned#\#}"
    cleaned="${cleaned# }"
    if [[ -z "$pending_comment" ]]; then
      pending_comment="$cleaned"
    else
      pending_comment="$pending_comment"$'\n'"$cleaned"
    fi
    continue
  fi
  # KEY=... line
  key="${line%%=*}"
  KEYS+=("$key")
  COMMENTS+=("$pending_comment")
  pending_comment=""
done < "$EXAMPLE_PATH"

[[ ${#KEYS[@]} -gt 0 ]] || die ".env.example declared zero variables; nothing to do."

# ---- prompt loop ----------------------------------------------------------

note "Populating .env from ${#KEYS[@]} variable(s) declared in .env.example."
echo

declare -a VALUES
for i in "${!KEYS[@]}"; do
  key="${KEYS[$i]}"
  comment="${COMMENTS[$i]}"

  echo "── $key ──"
  if [[ -n "$comment" ]]; then
    # Indent the help comment for readability
    printf '%s\n' "$comment" | sed 's/^/  /'
  fi

  # Mask input for keys that look secret-shaped
  read_args=(-r)
  if [[ "$key" =~ (KEY|TOKEN|SECRET|PASSWORD)$ ]]; then
    read_args+=(-s)
    printf '%s (input hidden): ' "$key"
    IFS= read "${read_args[@]}" value
    echo
  else
    printf '%s: ' "$key"
    IFS= read "${read_args[@]}" value
  fi

  if [[ -z "$value" ]]; then
    die "$key is empty; aborting without writing .env."
  fi
  VALUES+=("$value")
  echo
done

# ---- write .env -----------------------------------------------------------

{
  echo "# Generated by scripts/init.sh on $(date '+%Y-%m-%d %H:%M:%S %Z')."
  echo "# Edit by re-running scripts/init.sh, or by hand. This file is gitignored."
  echo
  for i in "${!KEYS[@]}"; do
    printf '%s=%s\n' "${KEYS[$i]}" "${VALUES[$i]}"
  done
} > "$ENV_PATH"

chmod 600 "$ENV_PATH"
note "Wrote $ENV_PATH (mode 600)."

# ---- optional Slack smoke test --------------------------------------------

slack_url=""
for i in "${!KEYS[@]}"; do
  if [[ "${KEYS[$i]}" == "SLACK_WEBHOOK_URL" ]]; then
    slack_url="${VALUES[$i]}"
    break
  fi
done

if [[ -n "$slack_url" ]]; then
  echo
  note "About to post a labelled '[JARVIS init]' setup notice to your Slack."
  note "Anyone in the target channel will see it."
  if ask_yes_no "Post the smoke-test message now?" "Y"; then
    payload='{"text":"[JARVIS init] setup complete '"$(date '+%Y-%m-%d %H:%M:%S %Z')"'"}'
    http_status=$(curl -sS -o /tmp/jarvis_init_resp -w '%{http_code}' \
      -H 'Content-Type: application/json' \
      -d "$payload" \
      "$slack_url" || true)
    if [[ "$http_status" =~ ^2[0-9][0-9]$ ]]; then
      note "Slack smoke test ok (HTTP $http_status)."
      rm -f /tmp/jarvis_init_resp
    else
      printf '[init] Slack smoke test FAILED (HTTP %s)\n' "$http_status" >&2
      printf '[init] response: ' >&2
      cat /tmp/jarvis_init_resp >&2 || true
      printf '\n' >&2
      rm -f /tmp/jarvis_init_resp
      die "Webhook did not accept the test message — verify the URL in .env."
    fi
  else
    note "Skipping smoke test."
  fi
fi

echo
note "Done. Next: edit config.yaml and profile.yaml to your taste, then run bash run.sh."
